sudo: false
cache: bundler
bundler_args: ""
script: "bundle exec rake spec"
rvm:
  - 1.8.7
  - 1.9.3
gemfile:
  - gemfiles/rails-2.3.gemfile
  - gemfiles/rails-3.0.gemfile
  - gemfiles/rails-3.2.gemfile
